version: 2
jobs: 
  security_checks: 
    docker: 
      - 
        image: "circleci/python:3.6.1"
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"requirements.txt\" }}"
            - v1-dependencies-
      - 
        run: 
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
          name: "install dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"requirements.txt\" }}"
          paths: 
            - ./venv
      - 
        run: 
          command: |
              . venv/bin/activate
              safety check
              bandit -r .
              prospector
          name: "run tests"
    working_directory: ~/repo
  unit_tests: 
    docker: 
      - 
        image: "circleci/python:3.6.1"
    steps: 
      - checkout
      - 
        restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"requirements.txt\" }}"
            - v1-dependencies-
      - 
        run: 
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
          name: "install dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"requirements.txt\" }}"
          paths: 
            - ./venv
      - 
        run: 
          command: |
              . venv/bin/activate
              python -m unittest
          name: "run tests"
      - 
        store_artifacts: 
          destination: test-reports
          path: test-reports
    working_directory: ~/repo

workflows:
  version: 2
  build_and_test: 
    jobs: 
      - security_checks
      - 
        unit_tests: 
          requires: 
            - security_checks
